server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: efexunn
    password: efexunn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
